VideoChallenge/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^', include('challenge.urls', namespace="challenge")),
]

challenge/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^home/$', views.HomeView.as_view(), name="home"),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.Logout.as_view(), name='logout'),


    url(r'^trending/$', views.TrendingView.as_view(), name="trending"),
    url(r'^done/$', views.DoneView.as_view(), name="done"),

]

challenge/models.py
# -*- coding: utf-8 -*-
# from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.db import models
from datetime import datetime, timedelta

from . import shortuuid


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    userID = models.IntegerField()
    
    def __str__(self):
        return self.user.username


class Challenge(models.Model):
    title = models.CharField(max_length=50, blank=False, null=False)
    description = models.TextField()
    owner = models.ForeignKey(UserProfile)
    start_datetime = models.DateTimeField()
    end_datetime = models.DateTimeField()
    when_created = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.title


class Entry(models.Model):
    challenge = models.ForeignKey(Challenge, null=False)
    title = models.CharField(max_length=50, blank=False, null=False)
    owner = models.ForeignKey(UserProfile, null=False)
    when_created = models.DateTimeField(default=datetime.now)
    # video

    def __str__(self):
        return self.title

    def votes(self):
        return self.vote.count()


class Vote(models.Model):
    user = models.ForeignKey(User, null=False)
    entry = models.ForeignKey(Entry, null=False)
    when_created = models.DateTimeField(default=datetime.now)


def generate_code():
    return shortuuid.uuid()

class InviteCode(models.Model):
    code = models.CharField(max_length=20,default=generate_code)
    challenge = models.ForeignKey(Challenge)
    used = models.BooleanField()

challenge/views.py
# -*- coding: utf-8 -*-
# from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

from .models import UserProfile


class IndexView(View):

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('challenge:home')
        else:
            return redirect('challenge:login')


class LoginView(View):

    def get(self, request):
        return render(request, 'challenge/login.html')


class Logout(View):
    # @login_required
    def get(self, request):
        logout(request)
        return redirect('challenge:index')


class HomeView(View):
    # @login_required
    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('challenge:login')

        fb_user = request.user
        try:
            facebook_login = fb_user.social_auth.get(provider='facebook')
        except:
            return redirect('challenge:index')

        fb_id = facebook_login.extra_data.get('id')

        try:
          user = UserProfile.objects.get(userID=fb_id)
        except UserProfile.DoesNotExist:
          user = UserProfile(user=request.user,userID=fb_id)
          user.save()

        return render(request, 'challenge/home.html')


class TrendingView(View):

    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('challenge:login')

        return render(request, 'challenge/trending.html')


class DoneView(View):

    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('challenge:login')

        return render(request, 'challenge/done.html')

templates/challenge/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'challenge/css/header.css' %}" />
    </head>

    <body>
        <header class="header-user-dropdown">
            <div class="header-limiter">
                <h1><a href="#">Video<span>Challenge</span></a></h1>
                <nav>
                    <a href="#">Home</a>
                    <a href="#">Trending</a>
                    <a href="#">Done</a>
                </nav>

                {# SEARCH FIELD #}
                {#<input type="text" name="search" placeholder="Search..">#}

                <div class="header-user-menu">
                    <img src="{% static 'challenge/images/user.png' %}" alt="User Image"/>
                    <ul>
                        <li><a href="#">Account</a></li>
                        <li><a href="{% url 'challenge:logout' %}" class="highlight">Logout</a></li>
                    </ul>
                </div>
            </div>
        </header>

        <div class="divider"></div>

        {% block content %}

        {% endblock %}
    </body>

</html>

templates/challenge/baselogin.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'challenge/css/login.css' %}" />
    </head>

    <body>

        {% block content %}

        {% endblock %}
    </body>

c

templates/challenge/done.html
{% extends "challenge/base.html" %}

{% block content %}
<h1>Done Section</h1>
{% endblock %}

templates/challenge/home.html
{% extends "challenge/base.html" %}

{% block content %}

</div>
<p>Hello {{ user.username }}!</p>
{% endblock %}

templates/challenge/index.html
{% extends "challenge/base.html" %}

{% block content %}

  <script>
    
    function statusChangeCallback(response) {
      console.log('statusChangeCallback');
      console.log(response);
      
      if (response.status === 'connected') {
        testAPI();
      } else {
        console.log("Cannot Login");
      }
    }

    // This function is called when someone finishes with the Login
    // Button.  See the onlogin handler attached to it in the sample
    // code below.
    function checkLoginState() {
      FB.getLoginStatus(function(response) {
        statusChangeCallback(response);
      });
    }


    window.fbAsyncInit = function() {
      FB.init({
        appId      : '615630245445357',
        cookie     : true,  // enable cookies to allow the server to access 
                            // the session
        xfbml      : true,  // parse social plugins on this page
        version    : 'v2.8' // use graph api version 2.8
      });
    
      // FB.getLoginStatus(function(response) {
      //   statusChangeCallback(response);
      // });

    };

    function loginFB() {
      FB.login(function(response){
        checkLoginState(response);
      });
    }

    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "https://connect.facebook.net/en_US/sdk.js";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

    // Here we run a very simple test of the Graph API after login is
    // successful.  See statusChangeCallback() for when this call is made.
    function testAPI() {
      console.log('Welcome!  Fetching your information.... ');
      FB.api('/me', function(response) {
        console.log('Successful login for: ' + response.name);
        console.log(response);
        
        var redirect_url = "";
        var params = {"id": response.id, "name": response.name};
        post(redirect_url, params);
      });
    }

    // TODO: send data of user to server; issue: csrf token
    function post(path, params) {
      method = "post"; // Set method to post by default if not specified.

      // The rest of this code assumes you are not using a library.
      // It can be made less wordy if you use one.
      var form = document.createElement("form");
      form.setAttribute("method", method);
      form.setAttribute("action", path);

      for(var key in params) {
        if(params.hasOwnProperty(key)) {
          var hiddenField = document.createElement("input");
          hiddenField.setAttribute("type", "hidden");
          hiddenField.setAttribute("name", key);
          hiddenField.setAttribute("value", params[key]);

          form.appendChild(hiddenField);
        }
      }

      document.body.appendChild(form);
      form.submit();
    }

  </script>

  <!--
    Below we include the Login Button social plugin. This button uses
    the JavaScript SDK to present a graphical Login button that triggers
    the FB.login() function when clicked.
  -->

  <!-- <fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
  </fb:login-button> -->

  <button class="fb-login" onclick="loginFB()">Login with Facebook</button>

  <!-- <div id="status"></div> -->

{% endblock %}

templates/challenge/login.html
{% extends "challenge/baselogin.html" %}

{% block content %}
  <div id="wrapper">
      <div class="join">Join Now!</div>
    	<div class="lock"></div>
	        <div class="clr"></div>
    	    	<div class="login-options">Choose on of the following sign up methods.</div>
                	<a class="twitter" href="#">Twitter</a>
                    <a class="facebook" href="{% url 'social:begin' 'facebook' %}">Facebook</a>
                    <a class="google" href="#">Google+</a>
                    <div class="clr"><hr /></div>
                    		<div class="mail-text">Or sign up using your email address.</div>
                            		<div class="forms">
                                    <form action="" method="get" name="register">
                                    <input name="fullname" type="text" value="Enter your full name..." size="70" onClick="border: 1px solid #30a8da;" id="username"/>
                                    <input name="email" type="text" value="Enter your email address..." size="70" onClick="border: 1px solid #30a8da;" id="mail"/>
                                    <input name="password" type="password" value="Enter a password..." size="70" onClick="border: 1px solid #30a8da;" id="password"/>
                                    </form>
                                    </div>
						<a class="create-acc" href="#">Create Account</a>
</div>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    </form>
{% endblock %}

templates/challenge/login2.html
<!DOCTYPE html>
<html>
    <head>
        <title>Login</title>
        <meta charset="UTF-8">
    </head>
    <body>
        <script>
          // This is called with the results from from FB.getLoginStatus().
          function statusChangeCallback(response) {
            console.log('statusChangeCallback');
            console.log(response);
            // The response object is returned with a status field that lets the
            // app know the current login status of the person.
            // Full docs on the response object can be found in the documentation
            // for FB.getLoginStatus().
            if (response.status === 'connected') {
              // Logged into your app and Facebook.
              // TODO: Check if user is logged in to site, if not, then "Login" >> "Continue as ____"
              testAPI();
            } else {
              // The person is not logged into your app or we are unable to tell.
              document.getElementById('status').innerHTML = 'Please log ' +
                'into this app.';
            }
          }

          // This function is called when someone finishes with the Login
          // Button.  See the onlogin handler attached to it in the sample
          // code below.
          function checkLoginState() {
            FB.getLoginStatus(function(response) {
              statusChangeCallback(response);
            });
          }


          window.fbAsyncInit = function() {
            FB.init({
              appId      : '615630245445357',
              cookie     : true,  // enable cookies to allow the server to access 
                                  // the session
              xfbml      : true,  // parse social plugins on this page
              version    : 'v2.8' // use graph api version 2.8
            });

            // Now that we've initialized the JavaScript SDK, we call 
            // FB.getLoginStatus().  This function gets the state of the
            // person visiting this page and can return one of three states to
            // the callback you provide.  They can be:
            //
            // 1. Logged into your app ('connected')
            // 2. Logged into Facebook, but not your app ('not_authorized')
            // 3. Not logged into Facebook and can't tell if they are logged into
            //    your app or not.
            //
            // These three cases are handled in the callback function.

            FB.getLoginStatus(function(response) {
              statusChangeCallback(response);
            });

          };

          // Load the SDK asynchronously
          (function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "https://connect.facebook.net/en_US/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);
          }(document, 'script', 'facebook-jssdk'));

          // Here we run a very simple test of the Graph API after login is
          // successful.  See statusChangeCallback() for when this call is made.
          function testAPI() {
            console.log('Welcome!  Fetching your information.... ');
            FB.api('/me', function(response) {
              console.log('Successful login for: ' + response.name);
              console.log(response);
              document.getElementById('status').innerHTML =
                'Thanks for logging in, ' + response.name + '!' + response.id;
                // TODO: Log fb user in to site, check if existing or not;
                // TODO: search about unique entity of fb users: is there a userId?
            });
          }
        </script>

        <!--
          Below we include the Login Button social plugin. This button uses
          the JavaScript SDK to present a graphical Login button that triggers
          the FB.login() function when clicked.
        -->

        <fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
        </fb:login-button>

        <div id="status">
        </div>

    </body>
</html>

templates/challenge/trending.html
{% extends "challenge/base.html" %}

{% block content %}
<h1>Trending Section</h1>
    <h1>Trending Section</h1>
    <h1>Trending Section</h1><h1>Trending Section</h1><h1>Trending Section</h1>
    <br><br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br><br><br>

    <h1>Trending Section</h1><h1>Trending Section</h1><h1>Trending Section</h1><h1>Trending Section</h1>

{% endblock %}